### ISSUE TITLE
Remix react breaks with 1.0.27, works with 1.0.26

### ISSUE THREAD

**Issue by phpb-com** [shiyiya/oplayer#16]
Hi again,

I ran into issues with my Remix React app after the upgrade to 1.0.27. This error pos-up once I click through to the video and then try to go back to the home page clicking the navigation. I did not look too deeply yet, but though it would help if I report it first. You may have an idea why.

```
TypeError: Cannot read properties of undefined (reading 'catch')
    at I.<anonymous> (http://127.0.0.1:8788/build/routes/video/$videoId-ZM2HA7D3.js:5077:41)
    at I.destroy (http://127.0.0.1:8788/build/routes/video/$videoId-ZM2HA7D3.js:4086:32)
    at http://127.0.0.1:8788/build/routes/video/$videoId-ZM2HA7D3.js:5604:52
    at safelyCallDestroy (http://127.0.0.1:8788/build/entry.client-B7WEPQOE.js:16274:13)
    at commitHookEffectListUnmount (http://127.0.0.1:8788/build/entry.client-B7WEPQOE.js:16401:19)
    at commitPassiveUnmountInsideDeletedTreeOnFiber (http://127.0.0.1:8788/build/entry.client-B7WEPQOE.js:17812:17)
    at commitPassiveUnmountEffectsInsideOfDeletedTree_begin (http://127.0.0.1:8788/build/entry.client-B7WEPQOE.js:17771:13)
    at commitPassiveUnmountEffects_begin (http://127.0.0.1:8788/build/entry.client-B7WEPQOE.js:17707:19)
    at commitPassiveUnmountEffects (http://127.0.0.1:8788/build/entry.client-B7WEPQOE.js:17695:11)
    at flushPassiveEffectsImpl (http://127.0.0.1:8788/build/entry.client-B7WEPQOE.js:18987:11)
```

**Comment by shiyiya** [comment]
https://github.com/shiyiya/oplayer/commit/00e66cd0c0a45928653030ee23eb0ff942ac3499#diff-6593ce7b068dd4ab9fdd9e4e2260e1ab9fedc7af44251167f3a934729122fb0dL73

Note that some APIs have changed.

**Comment by shiyiya** [comment]
v1.0.28 released.

**Comment by shiyiya** [comment]
What about https://oplayer.vercel.app ？

**Comment by shiyiya** [comment]
I cannot get valid information from the error

**Comment by shiyiya** [comment]
Can you provide the code to call oplayer?

**Comment by shiyiya** [comment]
Is this an oplayer error?

**Comment by shiyiya** [comment]
Wait, I found the reason for the error.

**Comment by shiyiya** [comment]
A new version has been released, try it out and thanks for the feedback!

**Comment by shiyiya** [comment]
```ts
import ui from '@oplayer/ui'
//....

/* Put it on top or wrap it in mome */
const hlsConfig: Partial<HlsConfig> = { }
const plugins = [ ]
/* *   **   *  */


export function OPlayer(props: ReactOPlayerProps) {
  
  return (
    <ReactPlayer
      plugins={plugins}
      {...props}
    />
  )
}

```

**Comment by shiyiya** [comment]
Currently they(`plugins`) are not responsive and the update will do nothing
